/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSlaRouteImport } from './routes/_auth.sla'
import { Route as AuthProfilesRouteImport } from './routes/_auth.profiles'
import { Route as AuthDemandsRouteImport } from './routes/_auth.demands'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthContractsRouteImport } from './routes/_auth.contracts'
import { Route as AuthCandidatesRouteImport } from './routes/_auth.candidates'
import { Route as AuthApprovalsRouteImport } from './routes/_auth.approvals'
import { Route as AuthAdminRouteImport } from './routes/_auth.admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSlaRoute = AuthSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfilesRoute = AuthProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDemandsRoute = AuthDemandsRouteImport.update({
  id: '/demands',
  path: '/demands',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContractsRoute = AuthContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCandidatesRoute = AuthCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AuthRoute,
} as any)
const AuthApprovalsRoute = AuthApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRoute
  '/approvals': typeof AuthApprovalsRoute
  '/candidates': typeof AuthCandidatesRoute
  '/contracts': typeof AuthContractsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/demands': typeof AuthDemandsRoute
  '/profiles': typeof AuthProfilesRoute
  '/sla': typeof AuthSlaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRoute
  '/approvals': typeof AuthApprovalsRoute
  '/candidates': typeof AuthCandidatesRoute
  '/contracts': typeof AuthContractsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/demands': typeof AuthDemandsRoute
  '/profiles': typeof AuthProfilesRoute
  '/sla': typeof AuthSlaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/admin': typeof AuthAdminRoute
  '/_auth/approvals': typeof AuthApprovalsRoute
  '/_auth/candidates': typeof AuthCandidatesRoute
  '/_auth/contracts': typeof AuthContractsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/demands': typeof AuthDemandsRoute
  '/_auth/profiles': typeof AuthProfilesRoute
  '/_auth/sla': typeof AuthSlaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/approvals'
    | '/candidates'
    | '/contracts'
    | '/dashboard'
    | '/demands'
    | '/profiles'
    | '/sla'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/approvals'
    | '/candidates'
    | '/contracts'
    | '/dashboard'
    | '/demands'
    | '/profiles'
    | '/sla'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/admin'
    | '/_auth/approvals'
    | '/_auth/candidates'
    | '/_auth/contracts'
    | '/_auth/dashboard'
    | '/_auth/demands'
    | '/_auth/profiles'
    | '/_auth/sla'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sla': {
      id: '/_auth/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof AuthSlaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profiles': {
      id: '/_auth/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AuthProfilesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/demands': {
      id: '/_auth/demands'
      path: '/demands'
      fullPath: '/demands'
      preLoaderRoute: typeof AuthDemandsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contracts': {
      id: '/_auth/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthContractsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/candidates': {
      id: '/_auth/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AuthCandidatesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/approvals': {
      id: '/_auth/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthApprovalsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthApprovalsRoute: typeof AuthApprovalsRoute
  AuthCandidatesRoute: typeof AuthCandidatesRoute
  AuthContractsRoute: typeof AuthContractsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDemandsRoute: typeof AuthDemandsRoute
  AuthProfilesRoute: typeof AuthProfilesRoute
  AuthSlaRoute: typeof AuthSlaRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthApprovalsRoute: AuthApprovalsRoute,
  AuthCandidatesRoute: AuthCandidatesRoute,
  AuthContractsRoute: AuthContractsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDemandsRoute: AuthDemandsRoute,
  AuthProfilesRoute: AuthProfilesRoute,
  AuthSlaRoute: AuthSlaRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
